### ISSUE TITLE
reveal.js checklist

### ISSUE THREAD

**Issue by atruskie** [ecoacoustics/website#16]
- [x] left justify normal text
- [x] center headings
- [x] add some slide layout shortcodes to make arranging content easier
    - [ ]  e.g. a two column layout
- [x] make sure the notes feature of reveal.js works
- [x] make sure there's a presentation mode button and it displays notes
- [x] make sure the print button works correctly (it should be using the print media style sheet and not calling window.print
- [x] ensure slide numbers are turned on
- [ ] consider custom plugins to install
    - [ ] https://github.com/rajgoel/reveal.js-plugins/tree/master/chalkboard
    - [ ] https://github.com/rajgoel/reveal.js-plugins/tree/master/customcontrols
    - [ ] https://github.com/SethosII/reveal.js-jump-plugin
    - [ ] https://github.com/denehyg/reveal.js-menu
